# Introductory NumPy lab: Please attempt all the questions and demo your answers to your intructor/TA within the due date.

Learning Objectives of this Lab:

* Create, manipulate, and reshape NumPy arrays.

* Perform statistical analysis and aggregation on arrays.

* Work with random data and array slicing.

* Understand and use array operations such as element-wise operations, conditional replacements, and aggregation.

* Gain practical skills with NumPy functions that are critical for data manipulation in Python.

These learning outcomes of these exercises are to provide students with a strong foundation in using NumPy for data manipulation, which will be essential for future data science, machine learning, and scientific computing applications.

# 1. Create a 3x3x3 array with random values

In [2]:
# Install matplotlib if not already installed
# %pip install matplotlib

import numpy as np
import matplotlib.pyplot as plt
array = np.random.rand(3, 3, 3)
print("3x3x3 array:\n", array)

3x3x3 array:
 [[[9.06716629e-01 4.25846134e-01 3.62137158e-01]
  [7.52641710e-01 3.75831100e-05 9.79063914e-01]
  [9.27575117e-01 9.54379568e-01 8.42090259e-01]]

 [[7.58743296e-01 4.59303643e-01 4.76432083e-01]
  [9.51327716e-01 4.25235089e-01 2.65076835e-01]
  [8.53800503e-01 7.54331299e-01 9.33775648e-01]]

 [[7.43358621e-02 3.15670293e-01 5.98898959e-01]
  [3.94737838e-01 1.41620052e-01 8.60514869e-02]
  [8.00491913e-01 2.96874671e-01 2.03665336e-01]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
matrix2 = np.diag([1, 2, 3, 4], k=-1)
print(matrix2)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
def print_checkerboard(rows, cols):
    for i in range(rows):
        for j in range(cols):
            if (i + j) % 2 == 0:
                print("X", end=" ")
            else:
                print("O", end=" ")
        print()
print_checkerboard(8, 8)

checkerboard = np.zeros((8, 8), dtype=int)
#this will create a checkerboard pattern, where 1s and 0s alternate by row and column
checkerboard[::2, ::2] = 1  # Fill even row, even col
checkerboard[1::2, 1::2] = 1  # Fill odd row, odd col

print("Checkerboard Pattern:\n", checkerboard)


X O X O X O X O 
O X O X O X O X 
X O X O X O X O 
O X O X O X O X 
X O X O X O X O 
O X O X O X O X 
X O X O X O X O 
O X O X O X O X 
Checkerboard Pattern:
 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4. Normalize a 5x5 random matrix

In [10]:
matrix3 = np.random.rand(5, 5)
min_val = matrix3.min()
max_val = matrix3.max()
normalized_matrix = (matrix3 - min_val) / (max_val - min_val)
print("Normalized Matrix:\n", normalized_matrix)

Normalized Matrix:
 [[0.05001589 0.83042531 0.9035978  0.50341678 0.41706843]
 [1.         0.12262299 0.44408289 0.44370331 0.06982105]
 [0.98245966 0.10242433 0.95102957 0.         0.4406456 ]
 [0.781509   0.29876415 0.80539835 0.05912035 0.50408629]
 [0.70142249 0.37651016 0.10321094 0.4791217  0.25363398]]


# 5.  How to find common values between two arrays?

refer and study the method `intersect1d`

In [9]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
#find common values

common_values = np.intersect1d(array, array2)
print("Common Values:\n", common_values)

Common Values:
 [1 2 3 4 5 6 7 8 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [10]:
from datetime import datetime, timedelta
#todays date
today = datetime.now()
#yesterday
yesterday = today - timedelta(days=1)
#tomorrow
tomorrow = today + timedelta(days=1)

#print
print("Today's Date:", today.strftime("%Y-%m-%d"))
print("Yesterday's Date:", yesterday.strftime("%Y-%m-%d"))
print("Tomorrow's Date:", tomorrow.strftime("%Y-%m-%d"))

Today's Date: 2025-04-02
Yesterday's Date: 2025-04-01
Tomorrow's Date: 2025-04-03


# 7. Consider two random array A and B, check if they are equal

In [15]:
#2 random arrays A and B, check if they are equal
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
if np.array_equal(A, B):
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are not equal.


# 8.Create random vector of size 20 and replace the maximum value by 1 and minimum value by -1

In [3]:
#random vector of size 20 and replace the max value by 1 and min value by -1
vector = np.random.rand(20)
max_index = vector.argmax() 
min_index = vector.argmin()
vector[max_index] = 1
vector[min_index] = -1
print("Modified Vector:\n", vector)

Modified Vector:
 [ 0.3241657   1.          0.77878128  0.25433765  0.71422354  0.51841172
  0.77908034  0.84628984  0.3376046   0.66535363  0.58575207  0.57189294
  0.81274745  0.06846924  0.15302821  0.60964863  0.23259641 -1.
  0.21869648  0.09623485]


# 9. How to print all the values of an array?

In [12]:
#print all values of an array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("All values in the array:\n", array)

All values in the array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# 10.Subtract the mean of each row of a matrix

In [4]:
#subtract the mean of each row of a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_means = matrix.mean(axis=1, keepdims=True)
normalized_matrix = matrix - row_means
print("Matrix after subtracting row means:\n", normalized_matrix)

Matrix after subtracting row means:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [5]:
#consider a given vector, how to add 1 to each element indexed by a second voctor. (careful with repeated indices)
vector = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 1, 2, 2, 3])  # Repeated index for element 2
vector[indices] += 1
print("Vector after adding 1 to indexed elements:\n", vector)

Vector after adding 1 to indexed elements:
 [2 3 4 5 5]


# 12.How to get the diagonal of a dot product?

In [6]:
#how to get the diagonal of a dot product?
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix1, matrix2)
diagonal = np.diag(dot_product)
print("Diagonal of the dot product:\n", diagonal)

Diagonal of the dot product:
 [19 50]


# 13.How to find the most frequent value in an array?

In [ ]:
#how to find the most frequent value in an array?
array = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique, counts = np.unique(array, return_counts=True) # Get unique values and their counts, returning counts is True
most_frequent = unique[counts.argmax()]
print("Most frequent value in the array:\n", most_frequent)

Most frequent value in the array:
 4


# 14.How to create a record array from a regular array?

In [13]:
#how to get a record array from a regular array?
array = np.array([(1, 'Alice', 25), (2, 'Bob', 30), (3, 'Charlie', 35)])
# Create a record array from the regular array by specifying the names of the fields
record_array = np.core.records.fromarrays(array.T, names='id,name,age')
print("regular array:\n", array)
print("Record array:\n", record_array)

regular array:
 [['1' 'Alice' '25']
 ['2' 'Bob' '30']
 ['3' 'Charlie' '35']]
Record array:
 [('1', 'Alice', '25') ('2', 'Bob', '30') ('3', 'Charlie', '35')]


## 15. Create an array with values ranging from 0 to 1 with a step of 0.1.

In [ ]:
#create an array with values ranging from 0 to 1 with a step of 0.1
#this will create an array with values from 0 to 1 (inclusive) with a step of 0.1
array = np.arange(0, 1.1, 0.1)  # Include 1.0 by using 1.1 as the stop value
print("Array with values ranging from 0 to 1 with a step of 0.1:\n", array)

Array with values ranging from 0 to 1 with a step of 0.1:
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


# 16. Create a 5x5 matrix and replace all the even numbers with 0.

In [23]:
#create a 5x5 matrix and replace all the even numbers with 0
matrix = np.random.randint(1, 100, size=(5, 5))
print("Original Matrix:\n", matrix)
matrix[matrix % 2 == 0] = 0  # Replace even numbers with 0
print("Matrix after replacing even numbers with 0:\n", matrix)

Original Matrix:
 [[27 52 89 13  8]
 [55 64 83 51  1]
 [61 91 44 84 25]
 [55 86 80 20 92]
 [63 39 87 83 94]]
Matrix after replacing even numbers with 0:
 [[27  0 89 13  0]
 [55  0 83 51  1]
 [61 91  0  0 25]
 [55  0  0  0  0]
 [63 39 87 83  0]]


# 17. Create an array with values 1 to 9, and then use np.reshape() to reshape it into a 3x3 matrix. Study the `reshape()` method to answer this question

# 18. Create a 1D array of random values and find the standard deviation and variance of the array. You can use Python's inbuilt methods `np.std()` and `np.var()` or write your own code for these methods.

# 19. Given an array of numbers, find the indices where the value is greater than a given threshold. Refer to how the method `np.where()` works to answer this question.

# 20. Create two random arrays of size 3x3 and compute their element-wise addition and subtraction.

In [25]:
#17. create an array with values 1 to 9, and then use np.reshape to reshape it into a 3x3 matrix
array = np.arange(1, 10)
reshaped_matrix = array.reshape(3, 3)  # Reshape into a 3x3 matrix
print("Reshaped Matrix:\n", reshaped_matrix)

#18. create a 1D array of random values and find the standard deviation and variance of the array.you can use np.std and np.var functions
array = np.random.rand(10)  # Create a 1D array of random values
std_dev = np.std(array)  # Calculate standard deviation
variance = np.var(array)  # Calculate variance
print("Array:\n", array)
print("Standard Deviation:\n", std_dev)
print("Variance:\n", variance)

#19. Given an array of numbers, find the indices where the value is greater than a given threshold.
array = np.array([1, 2, 3, 4, 5, 6])
threshold = 3
indices = np.where(array > threshold)[0]  # Get indices where values are greater than threshold
print("Indices where values are greater than threshold:\n", indices)

#20. Create two random arrays of size 3x3 and compute their element-wise addition and subtraction.
array1 = np.random.rand(3, 3)
array2 = np.random.rand(3, 3)
addition_result = array1 + array2  # Element-wise addition
subtraction_result = array1 - array2  # Element-wise subtraction
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Element-wise Addition Result:\n", addition_result)
print("Element-wise Subtraction Result:\n", subtraction_result)

Reshaped Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array:
 [0.00587257 0.31821338 0.45249767 0.88502084 0.56945938 0.08234925
 0.12805882 0.47925959 0.02596165 0.85735629]
Standard Deviation:
 0.309050008394169
Variance:
 0.09551190768843594
Indices where values are greater than threshold:
 [3 4 5]
Array 1:
 [[0.68503821 0.05218844 0.78868026]
 [0.43628869 0.52550239 0.67172215]
 [0.97915743 0.33162047 0.94615854]]
Array 2:
 [[0.86500602 0.91943511 0.55436708]
 [0.40432212 0.63797094 0.00426941]
 [0.21892864 0.41886262 0.34761908]]
Element-wise Addition Result:
 [[1.55004424 0.97162356 1.34304734]
 [0.84061081 1.16347333 0.67599156]
 [1.19808607 0.75048309 1.29377762]]
Element-wise Subtraction Result:
 [[-0.17996781 -0.86724667  0.23431319]
 [ 0.03196657 -0.11246854  0.66745274]
 [ 0.76022879 -0.08724215  0.59853945]]
